import Head from 'next/head'
import Image from 'next/image'
import ListaProductos from '../components/ListaProductos'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import { useRouter } from 'next/router'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Series y donde verlas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.pinimg.com/originals/7c/86/fc/7c86fc27cfa08fa94ea560b8603e48b4.png" />
      </Head>

      <Navbar/>
      <Hero/>
      <ListaProductos/>
      <Footer/>

    </div>
  )
}
