import React, { useState } from 'react'
import Box from '@mui/material/Box'
import TextField from '@mui/material/TextField'
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button'
import { Typography } from '@mui/material'
import { padding } from '@mui/system'
import useAuth from '../hook/useAuth'
import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Alerta from '../components/Alerta'

const Login = () => {
  const auth = useAuth()
  const router = useRouter()
  const [alerta, setAlerta] = useState(false)

   const [email, setEmail] = useState('')
   const [password, setPassword] = useState('')

  return (
    <>
    <Head>
        <title>Registrarse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://th.bing.com/th/id/R.1f950449af841f18d034941076fad10e?rik=d2ai81zfQo9Srw&pid=ImgRaw&r=0" />
      </Head>
      <Box className={styles.cardIndividual}
        component="form" backgroundColor="gray"
        sx={{
          maxWidth: '400px',
          height: '450px',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'space-evenly',
          border: '1px solid gray',
          borderRadius: '5px',
          '& > :not(style)': { m: 1, width: '25ch' },
        }}
      >
        <Typography
          sx={{
            color: 'white',
            textAlign: 'center',
          }}
        >
          {alerta && <Alerta mensaje = "¡Usuario registrado con éxito!"/>}
          <h2>REGISTRO</h2>
        </Typography>
        <TextField
          id="outlined-basic"
          label="Correo Electrónico"
          variant="outlined"
          onChange={(event) => setEmail(event.target.value)}
        />
        <TextField
          id="outlined-basic"
          label="Contraseña"
          variant="outlined"
          type="password"
          onChange={(event) => setPassword(event.target.value)}
        />
        <Stack spacing={2} direction="column">
          <Button
            variant="contained"
            onClick={() => {
              auth
                .registerWithEmailAndPassword(email, password)
                .then(() => {
                  setAlerta(true)
                  setTimeout(() => {
                    router.push('/login')
                  }, 4000)
                  
                })
                .catch((error) => {
                  console.log(error)
                })
            }}
          >
            Registrarse
          </Button>
          <p>O</p>
          <Button
            variant="contained"
            onClick={() => {
              auth
                .registerOrLoginWithGoogle()
                .then(() => {
                  router.push('/')
                })
                .catch((error) => {
                  console.log(error)
                })
            }}
          >
            Google
          </Button>
        </Stack>
      </Box>
    </>
  )
}

export default Login